config/routes.rb
Rails.application.routes.draw do

  resources :food_items
  get 'home/index'
  get "/pages/:page" => "pages#show"
  root 'home#index'
  get "/pages/contact", to: "pages#contact", as: "contact"
  get "/pages/menu", to: "pages#menu", as: "menu"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food_item.rb
class FoodItem < ApplicationRecord

acts_as_punchable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base




end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
  before_action :set_food_item, only: [:show, :edit, :update, :destroy]

  # GET /food_items
  # GET /food_items.json
  def index
    if params[:name]
      @food_items = FoodItem.where('name LIKE ?', "%#{params[:name]}%")
    elsif
      @food_items = FoodItem.order(sort_column + ' ' + sort_direction)
    else
      @food_items = FoodItem.all
    end




  end

  # GET /food_items/1
  # GET /food_items/1.json
  def show
    @food_item.punch(request)
  end

  # GET /food_items/new
  def new
    @food_item = FoodItem.new
  end

  # GET /food_items/1/edit
  def edit
  end

  # POST /food_items
  # POST /food_items.json
  def create
    @food_item = FoodItem.new(food_item_params)

    respond_to do |format|
      if @food_item.save
        format.html { redirect_to @food_item, notice: 'Food item was successfully created.' }
        format.json { render :show, status: :created, location: @food_item }
      else
        format.html { render :new }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_items/1
  # PATCH/PUT /food_items/1.json
  def update
    respond_to do |format|
      if @food_item.update(food_item_params)
        format.html { redirect_to @food_item, notice: 'Food item was successfully updated.' }
        format.json { render :show, status: :ok, location: @food_item }
      else
        format.html { render :edit }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_items/1
  # DELETE /food_items/1.json
  def destroy
    @food_item.destroy
    respond_to do |format|
      format.html { redirect_to food_items_url, notice: 'Food item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_item
      @food_item = FoodItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_item_params
      params.require(:food_item).permit(:name, :description, :price, :section, :image)
    end

    def sort_column
      # params[:sort] || "name"
      FoodItem.column_names.include?(params[:sort]) ? params[:sort] : "name"

    end

    def sort_direction
      # params[:direction] || "asc"
      %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
    end
  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contact
  end
  def show
    render template: "pages/#{params[:page]}"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    direction = (column == params[:sort] && params[:direction] == "asc") ? "desc" : "asc"
    link_to title, :sort => column, :direction => direction
  end
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/food_items/_form.html.erb
<%= form_with(model: food_item, local: true) do |form| %>
  <% if food_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food_item.errors.count, "error") %> prohibited this food_item from being saved:</h2>

      <ul>
      <% food_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :section %>
    <%= form.text_field :section %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/food_items/edit.html.erb
<h1>Editing Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Show', @food_item %> |
<%= link_to 'Back', food_items_path %>

app/views/food_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center">Menu</h1>

<div align="center"><p>Search for a menu item by name. Case counts:</p>
<%= form_tag(food_items_path, method: :get) do %>
<%= text_field_tag :name, params[:name] %>
  <%= submit_tag 'Search', name: nil %>
<% end %></div>
<br><br>
<div class = menu><table>
  <thead>
    <tr class="menulabel" id="tablelink">
      <th><%= sortable "name" %></th>
      <th>Description</th>
      <th><%= sortable "price" %></th>
      <th><%= sortable "section" %></th>
      <th>Photo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @food_items.each do |food_item| %>
        <tr>
          <td width='120px'><b><a href="food_items/<%= food_item.id %>"><%= food_item.name %></a></b></td>
          <td width='250px'><%= food_item.description %></td>
          <td width='50px' align='center'><%= food_item.price %></td>
          <td width='100px' align='center'><%= food_item.section %></td>
          <td width='200px' align='center'><img src="<%= food_item.image %>" width="150px" height="120px"></td>
        </tr>
    <% end %>
  </tbody>
</table></div>

<br>

app/views/food_items/index_original.html.erb
<p id="notice"><%= notice %></p>

<h1>Food Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Section</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @food_items.each do |food_item| %>
      <tr>
        <td><%= food_item.name %></td>
        <td><%= food_item.description %></td>
        <td><%= food_item.price %></td>
        <td><%= food_item.section %></td>
        <td><img src="<%= food_item.image %>" width="125px" height="100px"></td>
        <td><%= link_to 'Show', food_item %></td>
        <td><%= link_to 'Edit', edit_food_item_path(food_item) %></td>
        <td><%= link_to 'Destroy', food_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food Item', new_food_item_path %>

app/views/food_items/new.html.erb
<h1>New Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Back', food_items_path %>

app/views/food_items/show.html.erb
<p id="notice"><%= notice %></p>
<p>Number of views: <%= @food_item.hits %></p>
<p>
  <strong>Name:</strong>
  <%= @food_item.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @food_item.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @food_item.price %>
</p>

<p>
  <strong>Section:</strong>
  <%= @food_item.section %>
</p>

<p>
  <strong>Image:</strong>
  <img src="<%= @food_item.image %>" width="450px" height="350px">
</p>

<%= link_to 'Edit', edit_food_item_path(@food_item) %> |
<%= link_to 'Back', food_items_path %>

app/views/home/index.html.erb
<div class=welcome><h1>Welcome to The Tavern!</h1></div>
<p class="frontpage">Have a look at our menu please!</p>
<img src="https://www.asialifemagazine.com/vietnam/wp-content/uploads/sites/4/2015/11/The-Elephant-Phu-My-Hung-f.jpg"  width="800px" alt="The Tavern">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScottRestaurant</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class = nav><ul>
  <li class="active"><%= link_to 'Home', controller: 'home' %></li>
  <li><%= link_to 'Menu', controller: 'food_items' %></li>
  <li><%= link_to 'Contact', contact_path %></li>
  </ul>
  </div>


  <div class = container>
  <%= yield %>
  </div>

</body>
</html>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>The Tavern</p>
<p>Phone: +84 28 5410 3900</p>
<p>Address: R2-24 Hung Gia 3, Bui Bang Street,<br>Phu My Hung , Ho Chi Minh City</p>
<div class=googlemap><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7839.865306182265!2d106.69958400886246!3d10.739674009118525!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31752fbe0f93ab89%3A0xbb5e2063febdcbc9!2sThe+Tavern+PMH!5e0!3m2!1sen!2s!4v1535794763605" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe></div>